### ISSUE TITLE
SocketError: getaddrinfo with iOS Personal Hotspot

### ISSUE THREAD

**Issue by trevorturk** [socketry/async-http#107]
Apologies in advance for this vague issue report, but I thought I should post something just in case future Googlers run into this issue, or maybe someone has an idea and/or some ideas about how to debug.

When I'm using macOS 12.6 while connected my iOS 16.0.2 iPhone's "Personal Hotspot" with `Net::HTTP`, I'm able to make HTTP requests like so:

```
uri = URI('http://example.com/')
=> #<URI::HTTP http://example.com/>
Net::HTTP.get_response(uri)
=> #<Net::HTTPOK 200 OK readbody=true>
```

However, when using `Async::HTTP`, I get an error:

internet = Async::HTTP::Internet.new
=> #<Async::HTTP::Internet:0x000000010c44eeb0 @clients={}, @options={}>
Async { internet.get("https://example.com") }
13.56s     warn: Async::Task [oid=0x16684] [ec=0x16698] [pid=78449] [2022-10-03 15:10:21 -0500]
               | Task may have ended with unhandled exception.
               |   SocketError: getaddrinfo: nodename nor servname provided, or not known
               |   → /Users/trevorturk/.rbenv/versions/3.1.2/lib/ruby/3.1.0/resolv.rb:770 in `ip'
```

I noticed my macOS DNS settings looked like so:

<img width="212" alt="Screen Shot 2022-10-03 at 3 24 02 PM" src="https://user-images.githubusercontent.com/402/193674482-35faaf29-b0a9-4b25-acb4-b78874aadbdc.png">

...so I tried changing to use Cloudflare's `1.1.1.1` and then things worked as expected.

I'm happy enough with this setup since it appears to be working, but I wonder if other people might run into the issue going forward. If I can help testing/debugging somehow, please do let me know! Otherwise I may leave this issue open for a while and then close for future possible Googlers!

**Comment by ioquatix** [comment]
I think this is the same as https://github.com/socketry/async/issues/180 - can you confirm it's the IPv6 address causing problems? i.e. does it work with just 172.20.10.1 (similar to how you tested 1.1.1.1).

**Comment by trevorturk** [comment]
Thanks so much, sorry I missed that other issue. I tested and confirmed that `172.20.10.1` works. I noticed some debugging ideas in that other issue. Please let me know if there's anything you'd like me to test, or feel free to close this as a dupe. I'm subscribed to the other issue, so I'll see activity there as well. Thank you!

**Comment by ioquatix** [comment]
Can you try the IPv6 address just by itself and reproduce the failure? i.e. it's not the combination of two addresses that causes the issue but the presence of an IPv6 address that causes failure.

**Comment by trevorturk** [comment]
I tested with the following, doing my best to avoid typos, so we'd just be testing the auto-populated address:

![Screen Shot 2022-10-03 at 5 54 40 PM](https://user-images.githubusercontent.com/402/193700063-cdc59470-4f7c-4b34-ac08-6c879274b3dc.png)

...and the issue occurred: `SocketError: getaddrinfo: nodename nor servname provided, or not known` was raised. I think that's what you meant to test, but let me know!

**Comment by ioquatix** [comment]
Are you able to try on the latest release of macOS? I can't reproduce it locally.

**Comment by trevorturk** [comment]
I am still able to reproduce:

<img width="819" alt="Screenshot 2022-10-31 at 10 30 27 AM" src="https://user-images.githubusercontent.com/402/199046372-c57875a7-685f-4606-8cfc-ed9cd2bab364.png">

I'm also on the latest iOS version (not beta, but the latest release)

I'm not sure how to help reproduce, but please do let me know if you have any ideas, or if you'd like to screen share or anything like that!

**Comment by ioquatix** [comment]
Thanks, that's really helpful, at least I know it's something I should be able to reproduce.

**Comment by ioquatix** [comment]
Okay, here is my next question, are you able to reproduce the issue using a public IPv6 DNS resovler? e.g. CloudFlare has `2606:4700:4700::1111`. If you can reproduce the issue with that public server that is very helpful for me because then I should be able to set up my own environment to match.

**Comment by trevorturk** [comment]
I'm sorry to say that it seems I cannot reproduce the issue with `2606:4700:4700::1111` sorry!

**Comment by ioquatix** [comment]
Ahhh so it's something specific to some resolvers and not others!

**Comment by trevorturk** [comment]
It occurred to me today that I should ask if there's anything I can provide in terms of a description of my local environment, or if perhaps it would be helpful for me to test with a Docker environment I could share etc. Please do let me know if anything like that would be helpful!

**Comment by ioquatix** [comment]
The fact you can't reproduce it with some servers is helpful knowledge. What might be the next step is if I can some how log into your environment and poke around. But, let me try for a repro on my end.

**Comment by olivierlacan** [comment]
@ioquatix I just ran into this the other day and tried to run `Resolv.getaddress` on `bin/rails c` within the dev same environment as @trevorturk. 

```
Loading development environment (Rails 7.0.4.3)
irb(main):001:0> Resolv.getaddress "google.com"
=> "74.125.136.100"
```

I can also help with repros if needed. 

I put a `binding.irb` in the `resolv.rb` exception site and got this: 

```
irb(#<Resolv::DNS::Requester::UnconnectedUDP:0x000000010685e970>):004:0> Addrinfo.ip(host).ip_address
/Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:4:in `ip': getaddrinfo: nodename nor servname provided, or not known (SocketError)
	from /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:4:in `sender'
	from <internal:prelude>:5:in `irb'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:770:in `sender'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:527:in `block in fetch_resource'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:1126:in `block (3 levels) in resolv'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:1124:in `each'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:1124:in `block (2 levels) in resolv'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:1123:in `each'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:1123:in `block in resolv'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:1121:in `each'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:1121:in `resolv'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:521:in `fetch_resource'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:507:in `each_resource'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:402:in `each_address'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:116:in `block in each_address'
	from 3.2.2/lib/ruby/3.2.0/resolv.rb:115:in `each'
	... 30 levels...
irb(#<Resolv::DNS::Requester::UnconnectedUDP:0x000000010685e970>):005:0> host
=> "fe80::887:c7ff:fe62:d64%en0"
```

I have a feeling something about this `%en0` (network interface?!) in the ipv6 DNS hostname is not happy. Removing it works fine.
```
Addrinfo.ip("fe80::887:c7ff:fe62:d64").ip_address
=> "fe80::887:c7ff:fe62:d64"
```

**Comment by ioquatix** [comment]
I've created an issue in the resolv repo.

**Comment by olivierlacan** [comment]
Fairly sure I've isolated this behavior to within Async exclusively, so while it might be related to Resolv behavior I can only reproduce it within an Async context: 

```
irb(main):022:0> ::Resolv.getaddresses("google.com")
=> ["142.251.35.238", "2607:f8b0:4008:815::200e"]
irb(main):023:0> Async { puts ::Resolv.getaddresses("google.com") }
    2m     warn: Async::Task [oid=0x3c398] [ec=0x3c3ac] [pid=4196] [2023-04-26 13:57:23 -0400]
               | Task may have ended with unhandled exception.
               |   SocketError: getaddrinfo: nodename nor servname provided, or not known
               |   → /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:771 in `ip'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:771 in `sender'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:527 in `block in fetch_resource'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:1128 in `block (3 levels) in resolv'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:1126 in `each'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:1126 in `block (2 levels) in resolv'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:1125 in `each'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:1125 in `block in resolv'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:1123 in `each'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:1123 in `resolv'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:521 in `fetch_resource'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:507 in `each_resource'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:402 in `each_address'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:116 in `block in each_address'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:115 in `each'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:115 in `each_address'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:102 in `getaddresses'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/3.2.0/resolv.rb:51 in `getaddresses'
               |     (irb):23 in `block in <top (required)>'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-2.5.0/lib/async/task.rb:158 in `block in run'
               |     /Users/olivierlacan/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/async-2.5.0/lib/async/task.rb:310 in `block in schedule'
=> #<Async::Task:0x000000000003c398>
irb(main):024:0> RUBY_VERSION
=> "3.2.2"
```

**Comment by ioquatix** [comment]
Ruby 3.1 / Async 2+ uses the new `address_resolve` fiber scheduler hook. I think that could be the root cause of the issue.

cc @bruno-

**Comment by olivierlacan** [comment]
Scheduler was definitely part of the backtrace when I was started looking into this.

**Comment by ioquatix** [comment]
I believe this issue should be fixed by <https://github.com/socketry/async/pull/243>. It would be great if people who can reproduce it, can test it. I'll cut a new release of Async 2.x soon.

**Comment by trevorturk** [comment]
I'm not on AT&T anymore, so I haven't been able to reproduce for a while, but perhaps @olivierlacan can give it a shot?

**Comment by ioquatix** [comment]
Thanks everyone!
