### ISSUE TITLE
HTTP/2 Protocol::HPACK::CompressionError: Index 67 too large!

### ISSUE THREAD

**Issue by ioquatix** [socketry/async-http#71]
```
Failures:

  1) Async::HTTP::Client Async::HTTP::Protocol::HTTPS can request remote resource
     Failure/Error: self.receive_initial_headers(super, frame.end_stream?)
     
     Protocol::HPACK::CompressionError:
       Index 67 too large!
     # /home/samuel/.gem/ruby/2.7.1/gems/protocol-hpack-1.4.2/lib/protocol/hpack/context.rb:156:in `dereference'
     # /home/samuel/.gem/ruby/2.7.1/gems/protocol-hpack-1.4.2/lib/protocol/hpack/context.rb:182:in `decode'
     # /home/samuel/.gem/ruby/2.7.1/gems/protocol-hpack-1.4.2/lib/protocol/hpack/decompressor.rb:159:in `decode'
     # /home/samuel/.gem/ruby/2.7.1/gems/protocol-http2-0.14.2/lib/protocol/http2/connection.rb:129:in `decode_headers'
     # /home/samuel/.gem/ruby/2.7.1/gems/protocol-http2-0.14.2/lib/protocol/http2/stream.rb:292:in `process_headers'
     # ./lib/async/http/protocol/http2/stream.rb:76:in `process_headers'
     # /home/samuel/.gem/ruby/2.7.1/gems/protocol-http2-0.14.2/lib/protocol/http2/stream.rb:319:in `receive_headers'
     # /home/samuel/.gem/ruby/2.7.1/gems/protocol-http2-0.14.2/lib/protocol/http2/connection.rb:375:in `receive_headers'
     # /home/samuel/.gem/ruby/2.7.1/gems/protocol-http2-0.14.2/lib/protocol/http2/headers_frame.rb:82:in `apply'
     # /home/samuel/.gem/ruby/2.7.1/gems/protocol-http2-0.14.2/lib/protocol/http2/connection.rb:168:in `read_frame'
     # ./lib/async/http/protocol/http2/connection.rb:106:in `block in read_in_background'
     # /home/samuel/.gem/ruby/2.7.1/gems/async-1.29.0/lib/async/task.rb:263:in `block in make_fiber'
```

**Comment by ioquatix** [comment]
I have not seen this for a long time.
